export const liveMatches = [
  {
    id: 'm1',
    team1: 'India', flag1: '🇮🇳',
    team2: 'Australia', flag2: '🇦🇺',
    score1: '287/6 (48.2)',
    score2: '285/9 (50.0)',
    status: 'India needs 0 runs — India won by 4 wickets!',
    live: false,
    matchType: 'ODI',
    series: 'ICC Champions Trophy 2025',
    venue: 'Narendra Modi Stadium, Ahmedabad',
  },
  {
    id: 'm2',
    team1: 'Pakistan', flag1: '🇵🇰',
    team2: 'England', flag2: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    score1: '168/4 (16.0)',
    score2: '—',
    status: 'Pakistan batting — 1st Innings',
    live: true,
    matchType: 'T20I',
    series: 'Pakistan vs England T20I Series',
    venue: 'National Stadium, Karachi',
  },
  {
    id: 'm3',
    team1: 'South Africa', flag1: '🇿🇦',
    team2: 'New Zealand', flag2: '🇳🇿',
    score1: '320/8 (90.0)',
    score2: '210/5 (60.2)',
    status: 'New Zealand trail by 110 runs — Day 3',
    live: true,
    matchType: 'Test',
    series: 'SA vs NZ Test Series — 2nd Test',
    venue: 'SuperSport Park, Centurion',
  },
  {
    id: 'm4',
    team1: 'Sri Lanka', flag1: '🇱🇰',
    team2: 'Bangladesh', flag2: '🇧🇩',
    score1: '198/10 (44.3)',
    score2: '201/3 (38.1)',
    status: 'Bangladesh won by 7 wickets',
    live: false,
    matchType: 'ODI',
    series: 'Asia Cup 2025',
    venue: 'R.Premadasa Stadium, Colombo',
  },
  {
    id: 'm5',
    team1: 'West Indies', flag1: '🏝️',
    team2: 'Afghanistan', flag2: '🇦🇫',
    score1: '—',
    score2: '—',
    status: 'Match starts at 2:30 PM IST',
    live: false,
    upcoming: true,
    matchType: 'T20I',
    series: 'WI vs AFG T20I Series',
    venue: 'Providence Stadium, Guyana',
  },
];

export const seriesList = [
  {
    id: 's1',
    name: 'ICC Champions Trophy 2025',
    teams: ['India', 'Australia', 'Pakistan', 'England', 'South Africa', 'New Zealand', 'Bangladesh', 'Afghanistan'],
    startDate: '19 Feb 2025',
    endDate: '9 Mar 2025',
    type: 'ODI',
    status: 'Completed',
    host: 'Pakistan/UAE',
  },
  {
    id: 's2',
    name: 'IPL 2025',
    teams: ['MI', 'CSK', 'RCB', 'DC', 'KKR', 'PBKS', 'RR', 'SRH', 'LSG', 'GT'],
    startDate: '22 Mar 2025',
    endDate: '25 May 2025',
    type: 'T20',
    status: 'Ongoing',
    host: 'India',
  },
  {
    id: 's3',
    name: 'Pakistan vs England T20I Series',
    teams: ['Pakistan', 'England'],
    startDate: '22 Apr 2025',
    endDate: '30 Apr 2025',
    type: 'T20I',
    status: 'Ongoing',
    host: 'Pakistan',
  },
  {
    id: 's4',
    name: 'SA vs NZ Test Series',
    teams: ['South Africa', 'New Zealand'],
    startDate: '17 Apr 2025',
    endDate: '3 May 2025',
    type: 'Test',
    status: 'Ongoing',
    host: 'South Africa',
  },
  {
    id: 's5',
    name: 'Asia Cup 2025',
    teams: ['India', 'Pakistan', 'Sri Lanka', 'Bangladesh', 'Afghanistan', 'UAE'],
    startDate: '1 May 2025',
    endDate: '20 May 2025',
    type: 'ODI',
    status: 'Upcoming',
    host: 'Sri Lanka',
  },
  {
    id: 's6',
    name: 'Ireland vs Zimbabwe ODI Series',
    teams: ['Ireland', 'Zimbabwe'],
    startDate: '10 May 2025',
    endDate: '18 May 2025',
    type: 'ODI',
    status: 'Upcoming',
    host: 'Ireland',
  },
];

export const newsUpdates = [
  {
    id: 1,
    title: 'Rohit Sharma becomes first Indian captain to win Champions Trophy on home soil',
    time: '2 hours ago',
    category: 'Champions Trophy',
    image: 'https://picsum.photos/seed/cricket1/600/350',
  },
  {
    id: 2,
    title: 'Bumrah picks up career-best figures in T20Is, stuns England top order',
    time: '3 hours ago',
    category: 'T20 International',
    image: 'https://picsum.photos/seed/cricket2/600/350',
  },
  {
    id: 3,
    title: 'IPL 2025: CSK vs MI clash set to break viewership records — Preview',
    time: '4 hours ago',
    category: 'IPL 2025',
    image: 'https://picsum.photos/seed/cricket3/600/350',
  },
  {
    id: 4,
    title: 'Ben Stokes returns to Test cricket after hamstring recovery',
    time: '5 hours ago',
    category: 'England Cricket',
    image: 'https://picsum.photos/seed/cricket4/600/350',
  },
  {
    id: 5,
    title: 'Babar Azam regains ICC ODI batting top spot ahead of Asia Cup',
    time: '6 hours ago',
    category: 'ICC Rankings',
    image: 'https://picsum.photos/seed/cricket5/600/350',
  },
  {
    id: 6,
    title: 'Shubman Gill breaks Sachin Tendulkar\'s record for youngest ODI century-maker',
    time: '8 hours ago',
    category: 'Records',
    image: 'https://picsum.photos/seed/cricket6/600/350',
  },
  {
    id: 7,
    title: 'WPL 2025 Auction: Full list of sold and unsold players with prices',
    time: '10 hours ago',
    category: 'WPL',
    image: 'https://picsum.photos/seed/cricket7/600/350',
  },
  {
    id: 8,
    title: 'Rain threat looms large over final day of SA vs NZ Test in Centurion',
    time: '12 hours ago',
    category: 'Test Cricket',
    image: 'https://picsum.photos/seed/cricket8/600/350',
  },
];

export const iccRankings = {
  batting: {
    test: [
      { rank: 1, player: 'Joe Root', country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', rating: 921 },
      { rank: 2, player: 'Marnus Labuschagne', country: '🇦🇺 Australia', rating: 895 },
      { rank: 3, player: 'Steve Smith', country: '🇦🇺 Australia', rating: 880 },
      { rank: 4, player: 'Rohit Sharma', country: '🇮🇳 India', rating: 863 },
      { rank: 5, player: 'Kane Williamson', country: '🇳🇿 New Zealand', rating: 851 },
    ],
    odi: [
      { rank: 1, player: 'Babar Azam', country: '🇵🇰 Pakistan', rating: 882 },
      { rank: 2, player: 'Virat Kohli', country: '🇮🇳 India', rating: 868 },
      { rank: 3, player: 'Shubman Gill', country: '🇮🇳 India', rating: 835 },
      { rank: 4, player: 'David Warner', country: '🇦🇺 Australia', rating: 820 },
      { rank: 5, player: 'Fakhar Zaman', country: '🇵🇰 Pakistan', rating: 810 },
    ],
    t20: [
      { rank: 1, player: 'Suryakumar Yadav', country: '🇮🇳 India', rating: 910 },
      { rank: 2, player: 'Mohammad Rizwan', country: '🇵🇰 Pakistan', rating: 871 },
      { rank: 3, player: 'Travis Head', country: '🇦🇺 Australia', rating: 853 },
      { rank: 4, player: 'Phil Salt', country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', rating: 840 },
      { rank: 5, player: 'Glenn Maxwell', country: '🇦🇺 Australia', rating: 828 },
    ],
  },
  bowling: {
    test: [
      { rank: 1, player: 'Jasprit Bumrah', country: '🇮🇳 India', rating: 902 },
      { rank: 2, player: 'Pat Cummins', country: '🇦🇺 Australia', rating: 886 },
      { rank: 3, player: 'Kagiso Rabada', country: '🇿🇦 South Africa', rating: 871 },
      { rank: 4, player: 'R. Ashwin', country: '🇮🇳 India', rating: 860 },
      { rank: 5, player: 'Stuart Broad', country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', rating: 845 },
    ],
    odi: [
      { rank: 1, player: 'Jasprit Bumrah', country: '🇮🇳 India', rating: 878 },
      { rank: 2, player: 'Shaheen Afridi', country: '🇵🇰 Pakistan', rating: 862 },
      { rank: 3, player: 'Trent Boult', country: '🇳🇿 New Zealand', rating: 845 },
      { rank: 4, player: 'Mohammad Siraj', country: '🇮🇳 India', rating: 831 },
      { rank: 5, player: 'Mitchell Starc', country: '🇦🇺 Australia', rating: 820 },
    ],
    t20: [
      { rank: 1, player: 'Rashid Khan', country: '🇦🇫 Afghanistan', rating: 892 },
      { rank: 2, player: 'Jasprit Bumrah', country: '🇮🇳 India', rating: 875 },
      { rank: 3, player: 'Wanindu Hasaranga', country: '🇱🇰 Sri Lanka', rating: 860 },
      { rank: 4, player: 'Adil Rashid', country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', rating: 847 },
      { rank: 5, player: 'Shaheen Afridi', country: '🇵🇰 Pakistan', rating: 835 },
    ],
  },
  teams: {
    test: [
      { rank: 1, team: '🇦🇺 Australia', rating: 135, points: 3373 },
      { rank: 2, team: '🇮🇳 India', rating: 120, points: 3120 },
      { rank: 3, team: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', rating: 110, points: 2860 },
      { rank: 4, team: '🇳🇿 New Zealand', rating: 105, points: 2730 },
      { rank: 5, team: '🇿🇦 South Africa', rating: 99, points: 2574 },
    ],
    odi: [
      { rank: 1, team: '🇮🇳 India', rating: 118, points: 3068 },
      { rank: 2, team: '🇦🇺 Australia', rating: 112, points: 2912 },
      { rank: 3, team: '🇳🇿 New Zealand', rating: 108, points: 2808 },
      { rank: 4, team: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', rating: 105, points: 2730 },
      { rank: 5, team: '🇵🇰 Pakistan', rating: 100, points: 2600 },
    ],
    t20: [
      { rank: 1, team: '🇮🇳 India', rating: 263, points: 6838 },
      { rank: 2, team: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', rating: 258, points: 6708 },
      { rank: 3, team: '🇦🇺 Australia', rating: 254, points: 6604 },
      { rank: 4, team: '🇿🇦 South Africa', rating: 250, points: 6500 },
      { rank: 5, team: '🇵🇰 Pakistan', rating: 247, points: 6422 },
    ],
  },
};
